# Generated by Django 3.1.7 on 2021-03-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.TextField(choices=[('Trabalho', 'Trabalho'), ('Compras', 'Compras'), ('Aniversario', 'Aniversario'), ('Outro', 'Outro')], default='Outro'),
        ),
    ]
